### ISSUE TITLE
Why using key "id"?

### ISSUE THREAD

**Issue by mzaini30** [Taiwrash/dev-resume#3]
https://github.com/Taiwrash/dev-resume/blob/6b20f9cdde60a27666bc5403f26c9add4a2e4363/data.json#L17

Is `id` key unique? In my opinion, better remove this key.

**Comment by Taiwrash** [comment]
Thanks so much @mzaini30 , I purposely include it because I think of implementing another fixtures that require unique ID. Thanks so much I really appreciate this feedback and contributions

**Comment by mzaini30** [comment]
@Taiwrash If I'll PR, then, my id is 1?

**Comment by Taiwrash** [comment]
Thanks so much @mzaini30 I will effect the changes, thanks.
