### ISSUE TITLE
You have to add hacktoberfest topic

### ISSUE THREAD

**Issue by anwareset** [Taiwrash/dev-resume#43]
This is Ineligible Repository for HacktoberFest
What is that mean?

Every PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by Taiwrash** [comment]
I had received a lot of notifications on making changes as regards adding Label. Thanks so much for your notifications everyone, let's keep our contributions coming. Thanks I love you all

**Comment by anwareset** [comment]
It's not about label. But your repo's description. You have to add description, and "hacktoberfest" topic on it.
![2020-10-04-131858_334x147_scrot](https://user-images.githubusercontent.com/25749089/95008459-40d25100-0644-11eb-9d03-b02489ba28cf.png)

**Comment by Taiwrash** [comment]
Resolved
